#SITE CONFIGURATION

title: Andrew Weymouth
description: Digital Initiatives Librarian, Writer
repository: 
baseurl: 
url: "http://aweymo.github.io/base"

google_tag_manager: 

# SEO PLUGIN

social:
  name: Andrew Weymouth
  links:
    - https://www.instagram.com/andrewrweymouth/
    - https://vimeo.com/andrewrainsweymouth
    - https://www.linkedin.com/in/andrew-weymouth/
    - https://github.com/aweymo
    - https://letterboxd.com/aweymo/
    - https://andrewweymouth.bandcamp.com/
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Home', link: '/home'}
  - {name: 'CV', link: '/cv'}
  - {name: 'Creative', link: '/creative'}
  - {name: 'Contact', link: '/contact'}
  
email: andrewrainsweymouth@gmail.com
github_username: aweymo
instagram_username: andrewrweymouth
linkedin_username: andrew-weymouth
letterboxd_username: aweymo
vimeo_username: andrewrainsweymouth

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
